### ISSUE TITLE
not treating headers correctly

### ISSUE THREAD

**Issue by itamarorni** [Take-Some-Bytes/python_http_parser#1]
in the code there is:
`
split_header = hdr.split(":")

    if len(split_header) != 2:

      # Malformed header, move on.

      continue
`

some headers have more than one ":"
e.g. "user-agent**:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv**:**15.0) Gecko/20100101 Firefox/15.0.1:

**Comment by Take-Some-Bytes** [comment]
Thanks for catching that! This was just meant as a side project, so I didn't properly read the specs, but I'll see what I can do.

**Comment by itamarorni** [comment]
Hey, I created a branch with a new 'commit' to fix the problem. Would like to become a collaborator in order to plug in my fix and maybe add some more improvements later on ("Permission to Take-Some-Bytes/python_http_parser.git denied to itamarorni").

**Comment by Take-Some-Bytes** [comment]
If you have a potential fix for the problem, you can fork this repository, commit your changes, and open a pull request to this project. I don't feel it is appropriate right now to add additional collaborators, but I may later.

**Comment by Take-Some-Bytes** [comment]
Temporarily fixed with commit [#022615e](https://github.com/Take-Some-Bytes/python_http_parser/commit/022615e14bec71e92c3521242ef06ef6d1ede9e3), release [v0.2.1](https://github.com/Take-Some-Bytes/python_http_parser/releases/tag/v0.2.1).

**Comment by itamarorni** [comment]
#2 
This is the pull request
